version: "3.5"
services:
    cs:
        image: cs16ds/server:latest
        volumes:
            - VCS1.6:/opt/hlds/
        ports:
            - "26900:26900/udp"
            - "27020:27020/udp"
            - "27015:27015/udp"
            - "27015:27015"
        environment:
            - MAXPLAYERS=32
            - START_MAP=de_dust
            - "SERVER_NAME=VINA CS16 (NEW)"
            - START_MONEY=800
            - ADMIN_STEAM=0:1:103923358
            - FRIENDLY_FIRE=0
            - BUY_TIME=0.02
            - RESTART_ON_FAIL=0
        command: ["-autorestart","+log"]
volumes:
    VCS1.6:
